name             'octopus_ssh_tentacle_registration'
maintainer       'Alex Vernacchia'
maintainer_email 'alvernacchia@gmail.com'
license          'All rights reserved'
description      'handle tentacle registration for linux ssh servers'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.3.2'
chef_version     '>= 12'
issues_url       'https://github.com/vernak2539/octopus-ssh-tentacle-registration/issues'
source_url       'https://github.com/vernak2539/octopus-ssh-tentacle-registration'
supports         'centos'
